name: CI

on:
  # workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branches:
      - dev
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci"
      - uses: ./.github/actions/free-disk-space
      - uses: ./.github/actions/ubuntu-dependencies
      - name: Check compilation
        run: SKIP_WASM_BUILD=1 cargo check --workspace --locked
        timeout-minutes: 20

  clippy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci"
          save-if: "false"
      - uses: ./.github/actions/free-disk-space
      - uses: ./.github/actions/ubuntu-dependencies
      - name: Run clippy
        run: SKIP_WASM_BUILD=1 cargo clippy --all-targets --locked --workspace --quiet
        timeout-minutes: 15

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci"
          save-if: "false"
      - uses: ./.github/actions/free-disk-space
      - uses: ./.github/actions/ubuntu-dependencies
      - name: Run tests
        run: SKIP_WASM_BUILD=1 cargo test --workspace --locked
        timeout-minutes: 15
